### ISSUE TITLE
vf naming and relationship with pf

### ISSUE THREAD

**Issue by MartinForReal** [Mellanox/ofed-docker#20]
how to handle udev rules in ofed driver If I enabled sriov on mellanox nic? 
Any advice is appreciated!

**Comment by adrianchiris** [comment]
Hi @MartinForReal

I think This inquiry is not related to this project directly

one way of doing it is to name the device via udev using ID_NET_NAME_PATH
see : https://www.freedesktop.org/software/systemd/man/systemd.net-naming-scheme.html

**Comment by MartinForReal** [comment]
I agree, but It is a bit wired because udev daemon is running under host os. And when should I add devices rules in initialization scripts in container? How to refresh rules after kernel modules are loaded ?

**Comment by adrianchiris** [comment]
if you want to add udev rules it should be in the host and not container so udev daemon is able to load them.

the driver container today just loads the drivers.

**Comment by MartinForReal** [comment]
clear enough. Thanks for the info
